export const dynamic = "force-dynamic";

import { prisma } from "@/lib/prisma";
import { EXPLORER_ORG_ID } from "@/lib/org";
import { PageHeader } from "@/components/ui/page-header";
import { Badge } from "@/components/ui/badge";
import { JsonViewer, EmptyState } from "@/components/ui/misc";
import Link from "next/link";
import { formatDistanceToNow } from "date-fns";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";

async function getNode(id: string) {
  const orgId = EXPLORER_ORG_ID;
  return prisma.hydrationOntologyNode.findFirst({
    where: { id, orgId, deletedAt: null },
    include: {
      hydrationRun: {
        select: { id: true, status: true, stage: true, environment: true, completedAt: true },
      },
    },
  });
}

async function getSiblingCount(orgId: string, hydrationRunId: string, nodeType: string) {
  return prisma.hydrationOntologyNode.count({
    where: { orgId, hydrationRunId, nodeType, deletedAt: null },
  });
}

export default async function OntologyNodePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const node = await getNode(id);
  if (!node) notFound();

  const siblingCount = await getSiblingCount(EXPLORER_ORG_ID, node.hydrationRunId, node.nodeType);

  return (
    <div className="min-h-full">
      <PageHeader
        title={`Ontology Node · ${node.nodeKey}`}
        description={`${node.nodeType} node generated by hydration run ${node.hydrationRunId.slice(0, 12)}…`}
      />

      <div className="p-6 space-y-6">
        {/* Back */}
        <Link
          href="/ontology"
          className="inline-flex items-center gap-1.5 text-xs text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]"
        >
          <ArrowLeft size={12} />
          Back to Ontology
        </Link>

        {/* Metadata */}
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {[
            { label: "Node Type", value: <Badge>{node.nodeType}</Badge> },
            { label: "Node Key", value: <span className="font-mono text-xs">{node.nodeKey}</span> },
            { label: "Ontology Version", value: node.ontologyVersion ?? "—" },
            { label: "Vector Dimensions", value: node.vectorEmbedding.length > 0 ? `${node.vectorEmbedding.length}d` : "No vector" },
          ].map(({ label, value }) => (
            <div key={label} className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-3">
              <p className="text-[10px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">{label}</p>
              <div className="mt-1 text-sm text-[hsl(var(--foreground))]">{value}</div>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
          {/* Node Payload */}
          <div>
            <h2 className="mb-2 text-xs font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">
              Node Payload
            </h2>
            <JsonViewer data={node.nodePayload} />
          </div>

          {/* Hydration Run Context */}
          <div className="space-y-4">
            <div>
              <h2 className="mb-2 text-xs font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">
                Hydration Run
              </h2>
              <div className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-3 space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">ID</span>
                  <Link
                    href={`/hydration`}
                    className="font-mono text-[11px] text-[hsl(var(--primary))] hover:underline"
                  >
                    {node.hydrationRunId.slice(0, 20)}…
                  </Link>
                </div>
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">Status</span>
                  <Badge>{node.hydrationRun.status}</Badge>
                </div>
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">Stage</span>
                  <span className="font-mono text-[11px] text-[hsl(var(--foreground))]">{node.hydrationRun.stage}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">Environment</span>
                  <span className="font-mono text-[11px] text-[hsl(var(--foreground))]">{node.hydrationRun.environment}</span>
                </div>
                {node.hydrationRun.completedAt && (
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">Completed</span>
                    <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                      {formatDistanceToNow(node.hydrationRun.completedAt, { addSuffix: true })}
                    </span>
                  </div>
                )}
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">Siblings ({node.nodeType})</span>
                  <span className="font-mono text-[11px] text-[hsl(var(--foreground))]">{siblingCount.toLocaleString()}</span>
                </div>
              </div>
            </div>

            {/* Timestamps */}
            <div>
              <h2 className="mb-2 text-xs font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">
                Timestamps
              </h2>
              <div className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-3 space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">Created</span>
                  <span className="text-[11px] text-[hsl(var(--foreground))]">
                    {node.createdAt.toISOString()}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">Updated</span>
                  <span className="text-[11px] text-[hsl(var(--foreground))]">
                    {node.updatedAt.toISOString()}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
