import { Project, Task } from "@/types"

export const PLACEHOLDER_PROJECTS: Project[] = [
  {
    id: "sg2",
    name: "SpendGuru 2.0",
    slug: "sg2",
    description: "Next-gen negotiation intelligence platform",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
    _count: { tasks: 14, etaps: 0 },
  },
  {
    id: "cic",
    name: "Conversational Intelligence Core",
    slug: "cic",
    description: "AI runtime & engine ecosystem",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
    _count: { tasks: 22, etaps: 0 },
  },
  {
    id: "pmos",
    name: "PMOS",
    slug: "pmos",
    description: "Project management operating system",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
    _count: { tasks: 8, etaps: 0 },
  },
  {
    id: "profitia-pl",
    name: "profitia.pl",
    slug: "profitia-pl",
    description: "Corporate website & marketing",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
    _count: { tasks: 5, etaps: 0 },
  },
  {
    id: "spendguru-ai",
    name: "spendguru.ai",
    slug: "spendguru-ai",
    description: "Product landing & conversion site",
    status: "PAUSED",
    createdAt: new Date(),
    updatedAt: new Date(),
    _count: { tasks: 3, etaps: 0 },
  },
  {
    id: "leaxaro",
    name: "Leaxaro",
    slug: "leaxaro",
    description: "AI-native conversational intelligence platform",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
    _count: { tasks: 17, etaps: 0 },
  },
]

export const PLACEHOLDER_TASKS: Task[] = [
  {
    id: "t1",
    title: "ETAP 12 — Runtime Synthesis Layer",
    description: "Design and implement synthesis engines",
    type: "TASK",
    status: "ACTIVE",
    priority: "HIGH",
    projectId: "cic",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t2",
    title: "Neon DB connection stabilization",
    description: "Fix intermittent connection drops",
    type: "BUG",
    status: "BLOCKED",
    priority: "CRITICAL",
    projectId: "sg2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t3",
    title: "NCIC — Conversational session model",
    description: "Define and implement session persistence",
    type: "TASK",
    status: "ACTIVE",
    priority: "HIGH",
    projectId: "leaxaro",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t4",
    title: "profitia.pl homepage redesign",
    description: "Update hero section and services layout",
    type: "TASK",
    status: "PLANNED",
    priority: "MEDIUM",
    projectId: "profitia-pl",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t5",
    title: "PMOS starter kit scaffolding",
    description: "Initialize base project structure",
    type: "TASK",
    status: "PLANNED",
    priority: "MEDIUM",
    projectId: "pmos",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const PLACEHOLDER_BLOCKERS: Task[] = [
  {
    id: "b1",
    title: "Clerk production keys not issued",
    type: "BLOCKER",
    status: "BLOCKED",
    priority: "HIGH",
    projectId: "sg2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "b2",
    title: "Neon DB connection drops under load",
    type: "BLOCKER",
    status: "BLOCKED",
    priority: "CRITICAL",
    projectId: "cic",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
