import type { RendererProps } from "@/registry/renderer-registry";
import type { IntelligenceQueryResult } from "@/domains/intelligence/query";
import { PageHeader } from "@/components/ui/page-header";
import { Badge } from "@/components/ui/badge";
import { ConfidenceBar } from "@/components/ui/confidence-bar";
import { EmptyState } from "@/components/ui/misc";
import { formatDistanceToNow } from "date-fns";

const INTEL_TYPE_BADGE: Record<string, "default" | "success" | "warning" | "pcos" | "muted"> = {
  SHOULD_COST: "pcos",
  BENCHMARK: "warning",
  FORECASTING: "default",
  SUPPLIER_RISK: "muted",
  MACROECONOMIC: "success",
};

const INTEL_TYPE_DESC: Record<string, string> = {
  SHOULD_COST: "Should-cost model intelligence per commodity",
  BENCHMARK: "Market benchmark intelligence and trend analysis",
  FORECASTING: "Procurement forecasting models and projections",
  SUPPLIER_RISK: "Supplier risk assessment and risk signals",
  MACROECONOMIC: "Macroeconomic signal intelligence (CPI, PPI, etc.)",
};

export function IntelligenceRenderer({ data }: RendererProps) {
  const { units, byType } = data as IntelligenceQueryResult;

  return (
    <div className="min-h-full">
      <PageHeader
        title="Intelligence Units"
        description="Baseline procurement intelligence generated by PCOS-H3. Each unit answers: what does the system know about this subject?"
      />

      <div className="p-6 space-y-6">
        {byType.length > 0 && (
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {byType.map((t) => (
              <div
                key={t.intelligenceType}
                className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4"
              >
                <div className="flex items-center justify-between mb-2">
                  <Badge variant={INTEL_TYPE_BADGE[t.intelligenceType] ?? "default"}>
                    {t.intelligenceType}
                  </Badge>
                  <span className="font-mono text-base font-semibold text-[hsl(var(--foreground))]">
                    {t._count.id.toLocaleString()}
                  </span>
                </div>
                <p className="text-[11px] text-[hsl(var(--muted-foreground))] leading-snug">
                  {INTEL_TYPE_DESC[t.intelligenceType] ?? ""}
                </p>
                <div className="mt-3 space-y-1.5">
                  {t._avg.confidenceScore != null && (
                    <div>
                      <p className="text-[10px] text-[hsl(var(--muted-foreground))] mb-0.5">Avg Confidence</p>
                      <ConfidenceBar score={t._avg.confidenceScore} />
                    </div>
                  )}
                  {t._avg.dataQualityScore != null && (
                    <div>
                      <p className="text-[10px] text-[hsl(var(--muted-foreground))] mb-0.5">Avg Data Quality</p>
                      <ConfidenceBar score={t._avg.dataQualityScore} />
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {units.length === 0 ? (
          <EmptyState
            title="No intelligence units found"
            description="Run the PCOS-H3 hydration pipeline to generate intelligence units."
          />
        ) : (
          <div className="rounded-lg border border-[hsl(var(--border))] overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[hsl(var(--border))] bg-[hsl(var(--secondary))]">
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Type</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Subject</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Confidence</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Data Quality</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Valid Window</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Payload Keys</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Created</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[hsl(var(--border))]">
                {units.map((unit) => {
                  const payloadKeys = unit.intelligencePayload
                    ? Object.keys(unit.intelligencePayload as Record<string, unknown>).slice(0, 3)
                    : [];
                  const isExpired = unit.validUntil && unit.validUntil < new Date();
                  return (
                    <tr
                      key={unit.id}
                      className="bg-[hsl(var(--card))] transition-colors hover:bg-[hsl(var(--accent))]"
                    >
                      <td className="px-4 py-2.5">
                        <Badge variant={INTEL_TYPE_BADGE[unit.intelligenceType] ?? "default"}>
                          {unit.intelligenceType}
                        </Badge>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="font-mono text-xs text-[hsl(var(--foreground))]">{unit.subjectId}</span>
                      </td>
                      <td className="px-4 py-2.5">
                        <ConfidenceBar score={unit.confidenceScore} />
                      </td>
                      <td className="px-4 py-2.5">
                        <ConfidenceBar score={unit.dataQualityScore} />
                      </td>
                      <td className="px-4 py-2.5">
                        {unit.validFrom || unit.validUntil ? (
                          <div className="text-[10px]">
                            {unit.validFrom && (
                              <span className="text-[hsl(var(--muted-foreground))]">
                                From {unit.validFrom.toISOString().split("T")[0]}
                              </span>
                            )}
                            {unit.validUntil && (
                              <span className={isExpired ? "text-[hsl(0_84%_65%)]" : "text-[hsl(var(--muted-foreground))]"}>
                                {" "}→ {unit.validUntil.toISOString().split("T")[0]}
                                {isExpired && " (expired)"}
                              </span>
                            )}
                          </div>
                        ) : (
                          <span className="text-[11px] text-[hsl(var(--muted-foreground))]">—</span>
                        )}
                      </td>
                      <td className="px-4 py-2.5">
                        <div className="flex flex-wrap gap-1">
                          {payloadKeys.map((k) => (
                            <span
                              key={k}
                              className="rounded bg-[hsl(var(--secondary))] px-1 py-0.5 font-mono text-[10px] text-[hsl(var(--muted-foreground))]"
                            >
                              {k}
                            </span>
                          ))}
                        </div>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                          {formatDistanceToNow(unit.createdAt, { addSuffix: true })}
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            {units.length === 200 && (
              <div className="border-t border-[hsl(var(--border))] px-4 py-2 text-center">
                <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                  Showing first 200 intelligence units.
                </span>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
