import type { RendererProps } from "@/registry/renderer-registry";
import type { MemoryQueryResult } from "@/domains/memory/query";
import { PageHeader } from "@/components/ui/page-header";
import { Badge } from "@/components/ui/badge";
import { ConfidenceBar } from "@/components/ui/confidence-bar";
import { EmptyState } from "@/components/ui/misc";
import { formatDistanceToNow } from "date-fns";

const MEMORY_TYPE_BADGE: Record<string, "default" | "success" | "warning" | "pcos" | "muted"> = {
  SUPPLIER: "default",
  NEGOTIATION: "pcos",
  CONTEXTUAL: "muted",
  OPERATIONAL: "success",
};

const MEMORY_TYPE_DESC: Record<string, string> = {
  SUPPLIER: "Persistent supplier relationship and risk memory",
  NEGOTIATION: "Active and historical negotiation context memory",
  CONTEXTUAL: "Operational context and situational memory",
  OPERATIONAL: "Runtime operational state and process memory",
};

export function MemoryRenderer({ data }: RendererProps) {
  const { units, byType } = data as MemoryQueryResult;

  return (
    <div className="min-h-full">
      <PageHeader
        title="Cognition Memory"
        description="Persistent procurement memory units generated by the PCOS-H3 hydration pipeline. What the system remembers about suppliers, negotiations, and operational context."
      />

      <div className="p-6 space-y-6">
        {byType.length > 0 && (
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {byType.map((t) => (
              <div
                key={t.memoryType}
                className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4"
              >
                <div className="flex items-center justify-between mb-2">
                  <Badge variant={MEMORY_TYPE_BADGE[t.memoryType] ?? "default"}>
                    {t.memoryType}
                  </Badge>
                  <span className="font-mono text-base font-semibold text-[hsl(var(--foreground))]">
                    {t._count.id.toLocaleString()}
                  </span>
                </div>
                <p className="text-[11px] text-[hsl(var(--muted-foreground))] leading-snug">
                  {MEMORY_TYPE_DESC[t.memoryType] ?? ""}
                </p>
                {t._avg.confidenceScore != null && (
                  <div className="mt-2">
                    <p className="mb-1 text-[10px] text-[hsl(var(--muted-foreground))]">Avg Confidence</p>
                    <ConfidenceBar score={t._avg.confidenceScore} />
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {units.length === 0 ? (
          <EmptyState
            title="No cognition memory found"
            description="Run the PCOS-H3 hydration pipeline to generate memory units."
          />
        ) : (
          <div className="rounded-lg border border-[hsl(var(--border))] overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[hsl(var(--border))] bg-[hsl(var(--secondary))]">
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Type</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Subject</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Memory Key</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Confidence</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Temporal Context</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Payload Keys</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Created</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[hsl(var(--border))]">
                {units.map((unit) => {
                  const payloadKeys = unit.memoryPayload
                    ? Object.keys(unit.memoryPayload as Record<string, unknown>).slice(0, 3)
                    : [];
                  return (
                    <tr
                      key={unit.id}
                      className="bg-[hsl(var(--card))] transition-colors hover:bg-[hsl(var(--accent))]"
                    >
                      <td className="px-4 py-2.5">
                        <Badge variant={MEMORY_TYPE_BADGE[unit.memoryType] ?? "default"}>
                          {unit.memoryType}
                        </Badge>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="font-mono text-xs text-[hsl(var(--foreground))]">
                          {unit.subjectId}
                        </span>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">
                          {unit.memoryKey.length > 40 ? unit.memoryKey.slice(0, 40) + "…" : unit.memoryKey}
                        </span>
                      </td>
                      <td className="px-4 py-2.5">
                        <ConfidenceBar score={unit.confidenceScore} />
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                          {unit.temporalContext ?? "—"}
                        </span>
                      </td>
                      <td className="px-4 py-2.5">
                        <div className="flex flex-wrap gap-1">
                          {payloadKeys.map((k) => (
                            <span
                              key={k}
                              className="rounded bg-[hsl(var(--secondary))] px-1 py-0.5 font-mono text-[10px] text-[hsl(var(--muted-foreground))]"
                            >
                              {k}
                            </span>
                          ))}
                        </div>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                          {formatDistanceToNow(unit.createdAt, { addSuffix: true })}
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            {units.length === 200 && (
              <div className="border-t border-[hsl(var(--border))] px-4 py-2 text-center">
                <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                  Showing first 200 memory units.
                </span>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
