import type { RendererProps } from "@/registry/renderer-registry";
import type { OntologyQueryResult } from "@/domains/ontology/query";
import { PageHeader } from "@/components/ui/page-header";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/misc";
import Link from "next/link";
import { formatDistanceToNow } from "date-fns";

const NODE_TYPE_BADGE: Record<string, "default" | "success" | "warning" | "pcos" | "muted"> = {
  SUPPLIER: "default",
  CATEGORY: "muted",
  BENCHMARK: "pcos",
  PRODUCT: "success",
  COST_COMPONENT: "warning",
};

export function OntologyRenderer({ data }: RendererProps) {
  const { nodes, byType } = data as OntologyQueryResult;

  return (
    <div className="min-h-full">
      <PageHeader
        title="Ontology Explorer"
        description="Versioned procurement knowledge graph nodes generated by the PCOS-H3 hydration pipeline."
      />

      <div className="p-6 space-y-6">
        {byType.length > 0 && (
          <div className="flex flex-wrap gap-2">
            {byType.map((t) => (
              <div
                key={t.nodeType}
                className="flex items-center gap-2 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-3 py-2"
              >
                <Badge variant={NODE_TYPE_BADGE[t.nodeType] ?? "default"}>
                  {t.nodeType}
                </Badge>
                <span className="font-mono text-sm font-medium text-[hsl(var(--foreground))]">
                  {t._count.id.toLocaleString()}
                </span>
              </div>
            ))}
          </div>
        )}

        {nodes.length === 0 ? (
          <EmptyState
            title="No ontology nodes found"
            description="Run the PCOS-H3 hydration pipeline to generate ontology nodes."
          />
        ) : (
          <div className="rounded-lg border border-[hsl(var(--border))] overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[hsl(var(--border))] bg-[hsl(var(--secondary))]">
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Type</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Key</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Version</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Payload Keys</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Vector Dim</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Created</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[hsl(var(--border))]">
                {nodes.map((node) => {
                  const payloadKeys = node.nodePayload
                    ? Object.keys(node.nodePayload as Record<string, unknown>).slice(0, 4)
                    : [];
                  return (
                    <tr
                      key={node.id}
                      className="bg-[hsl(var(--card))] transition-colors hover:bg-[hsl(var(--accent))]"
                    >
                      <td className="px-4 py-2.5">
                        <Badge variant={NODE_TYPE_BADGE[node.nodeType] ?? "default"}>
                          {node.nodeType}
                        </Badge>
                      </td>
                      <td className="px-4 py-2.5">
                        <Link
                          href={`/ontology/${node.id}`}
                          className="font-mono text-xs text-[hsl(var(--primary))] hover:underline"
                        >
                          {node.nodeKey}
                        </Link>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">
                          {node.ontologyVersion ?? "—"}
                        </span>
                      </td>
                      <td className="px-4 py-2.5">
                        <div className="flex flex-wrap gap-1">
                          {payloadKeys.map((k) => (
                            <span
                              key={k}
                              className="rounded bg-[hsl(var(--secondary))] px-1 py-0.5 font-mono text-[10px] text-[hsl(var(--muted-foreground))]"
                            >
                              {k}
                            </span>
                          ))}
                          {Object.keys(node.nodePayload as Record<string, unknown>).length > 4 && (
                            <span className="text-[10px] text-[hsl(var(--muted-foreground))]">
                              +{Object.keys(node.nodePayload as Record<string, unknown>).length - 4} more
                            </span>
                          )}
                        </div>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">
                          {node.vectorEmbedding.length > 0 ? node.vectorEmbedding.length : "—"}
                        </span>
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                          {formatDistanceToNow(node.createdAt, { addSuffix: true })}
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            {nodes.length === 200 && (
              <div className="border-t border-[hsl(var(--border))] px-4 py-2 text-center">
                <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                  Showing first 200 nodes. Use filter to narrow results.
                </span>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
