import type { RendererProps } from "@/registry/renderer-registry";
import type { RetrievalQueryResult } from "@/domains/retrieval/query";
import { PageHeader } from "@/components/ui/page-header";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/misc";
import { formatDistanceToNow } from "date-fns";

const INDEX_TYPE_BADGE: Record<string, "default" | "success" | "warning" | "pcos" | "muted"> = {
  PROCUREMENT: "default",
  SEMANTIC: "pcos",
  GRAPH: "success",
  CONTEXTUAL: "warning",
};

const INDEX_TYPE_DESC: Record<string, string> = {
  PROCUREMENT: "Structured procurement entity documents",
  SEMANTIC: "Semantic content for vector similarity retrieval",
  GRAPH: "Graph topology documents for graph traversal",
  CONTEXTUAL: "Contextual documents for RAG assembly",
};

export function RetrievalRenderer({ data }: RendererProps) {
  const { docs, byType, withEmbedding } = data as RetrievalQueryResult;
  const totalIndexed = byType.reduce((a, t) => a + t._count.id, 0);

  return (
    <div className="min-h-full">
      <PageHeader
        title="Retrieval Documents"
        description="Indexed retrieval documents generated by PCOS-H3. These form the retrieval substrate for CIC context assembly."
      />

      <div className="p-6 space-y-6">
        {byType.length > 0 && (
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {byType.map((t) => (
              <div
                key={t.indexType}
                className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4"
              >
                <div className="flex items-center justify-between mb-2">
                  <Badge variant={INDEX_TYPE_BADGE[t.indexType] ?? "default"}>
                    {t.indexType}
                  </Badge>
                  <span className="font-mono text-base font-semibold text-[hsl(var(--foreground))]">
                    {t._count.id.toLocaleString()}
                  </span>
                </div>
                <p className="text-[11px] text-[hsl(var(--muted-foreground))] leading-snug">
                  {INDEX_TYPE_DESC[t.indexType] ?? ""}
                </p>
              </div>
            ))}
          </div>
        )}

        {totalIndexed > 0 && (
          <div className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-4 py-3">
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-xs text-[hsl(var(--muted-foreground))]">
                Embedding coverage ({withEmbedding.toLocaleString()} / {totalIndexed.toLocaleString()} documents)
              </span>
              <span className="font-mono text-xs text-[hsl(var(--foreground))]">
                {Math.round((withEmbedding / totalIndexed) * 100)}%
              </span>
            </div>
            <div className="h-1.5 w-full overflow-hidden rounded-full bg-[hsl(var(--secondary))]">
              <div
                className="h-full rounded-full bg-[hsl(var(--primary))]"
                style={{ width: `${Math.round((withEmbedding / totalIndexed) * 100)}%` }}
              />
            </div>
          </div>
        )}

        {docs.length === 0 ? (
          <EmptyState
            title="No retrieval documents found"
            description="Run the PCOS-H3 hydration pipeline to generate retrieval documents."
          />
        ) : (
          <div className="rounded-lg border border-[hsl(var(--border))] overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[hsl(var(--border))] bg-[hsl(var(--secondary))]">
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Index Type</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Document Type</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Document ID</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Tokens</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Embedded</th>
                  <th className="px-4 py-2.5 text-left text-[11px] font-medium uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Created</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[hsl(var(--border))]">
                {docs.map((doc) => (
                  <tr
                    key={doc.id}
                    className="bg-[hsl(var(--card))] transition-colors hover:bg-[hsl(var(--accent))]"
                  >
                    <td className="px-4 py-2.5">
                      <Badge variant={INDEX_TYPE_BADGE[doc.indexType] ?? "default"}>
                        {doc.indexType}
                      </Badge>
                    </td>
                    <td className="px-4 py-2.5">
                      <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">
                        {doc.documentType}
                      </span>
                    </td>
                    <td className="px-4 py-2.5">
                      <span className="font-mono text-xs text-[hsl(var(--foreground))]">
                        {doc.documentId.length > 36 ? doc.documentId.slice(0, 36) + "…" : doc.documentId}
                      </span>
                    </td>
                    <td className="px-4 py-2.5">
                      <span className="font-mono text-[11px] text-[hsl(var(--muted-foreground))]">
                        {doc.searchableTokens.length.toLocaleString()}
                      </span>
                    </td>
                    <td className="px-4 py-2.5">
                      {doc.embeddingRef ? (
                        <Badge variant="success">✓</Badge>
                      ) : (
                        <span className="text-[11px] text-[hsl(var(--muted-foreground))]">—</span>
                      )}
                    </td>
                    <td className="px-4 py-2.5">
                      <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                        {formatDistanceToNow(doc.createdAt, { addSuffix: true })}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {docs.length === 200 && (
              <div className="border-t border-[hsl(var(--border))] px-4 py-2 text-center">
                <span className="text-[11px] text-[hsl(var(--muted-foreground))]">
                  Showing first 200 documents.
                </span>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
