export const PREFERRED_HISTORICAL_VERIFICATION_ORIGIN_START_DATE = '2024-01-01'
export const MINIMUM_ADAPTIVE_HISTORICAL_VERIFICATION_ORIGINS = 24
export const ADAPTIVE_HISTORICAL_VERIFICATION_ORIGIN_POLICY_VERSION =
  'ADAPTIVE_PREFERRED_2024_MINIMUM_24@historical-verification-origin-policy-v1'
