#!/usr/bin/env node
/**
 * PCOS Explorer — Prisma Schema Sync Script
 *
 * Problem: pcos-explorer (Prisma 7) and pcos-runtime (Prisma 6) cannot share
 * a schema because generator blocks are incompatible. This script makes the
 * runtime schema the SOT: it reads the runtime schema, extracts all H-layer
 * model blocks, and writes a Prisma 7-compatible explorer schema.
 *
 * Usage:
 *   node scripts/sync-schema.mjs          # sync + overwrite
 *   node scripts/sync-schema.mjs --check  # dry-run: exit 1 if drift detected
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const RUNTIME_SCHEMA = resolve(
  __dirname,
  "../../pcos-runtime/prisma/schema.prisma"
);
const EXPLORER_SCHEMA = resolve(ROOT, "prisma/schema.prisma");

const CHECK_MODE = process.argv.includes("--check");

// ── Explorer Prisma 7 generator + datasource header ─────────────────────────
const EXPLORER_HEADER = `// =============================================================================
// PCOS Explorer — Prisma Schema (AUTO-GENERATED — DO NOT EDIT MANUALLY)
// Generated by: scripts/sync-schema.mjs
// Source of Truth: apps/pcos-runtime/prisma/schema.prisma
//
// To update: run \`npm run db:sync\`
// =============================================================================

generator client {
  provider = "prisma-client"
  output   = "../src/generated/prisma"
}

// NOTE: datasource URL is defined in prisma.config.ts (Prisma 7 requirement)
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

// ── Model/enum extraction ────────────────────────────────────────────────────
function extractBlocks(source) {
  const lines = source.split("\n");
  const blocks = [];
  let current = null;
  let depth = 0;

  for (const line of lines) {
    const modelMatch = line.match(/^(model|enum)\s+(\w+)\s*\{/);
    if (!current && modelMatch) {
      current = { type: modelMatch[1], name: modelMatch[2], lines: [line] };
      depth = 1;
      continue;
    }
    if (current) {
      current.lines.push(line);
      for (const ch of line) {
        if (ch === "{") depth++;
        else if (ch === "}") depth--;
      }
      if (depth === 0) {
        blocks.push({ ...current, text: current.lines.join("\n") });
        current = null;
      }
    }
  }
  return blocks;
}

// Models/enums relevant to the Explorer (H-layer + validation + promotion)
const H_LAYER_PREFIXES = [
  "Hydration",
  "Cognition",
  "Promotion",
  "Validation",
  "Sandbox",
];

function isExplorerRelevant(name) {
  return H_LAYER_PREFIXES.some(
    (prefix) => name.startsWith(prefix) || name.includes(prefix)
  );
}

// ── Main ─────────────────────────────────────────────────────────────────────
const runtimeSource = readFileSync(RUNTIME_SCHEMA, "utf-8");
const blocks = extractBlocks(runtimeSource);

const relevant = blocks.filter((b) => isExplorerRelevant(b.name));

if (relevant.length === 0) {
  console.error(
    "[sync-schema] ERROR: No H-layer blocks found in runtime schema. Check paths."
  );
  process.exit(1);
}

const generated =
  EXPLORER_HEADER + relevant.map((b) => b.text).join("\n\n") + "\n";

const newHash = createHash("sha256").update(generated).digest("hex");

let existingHash = null;
try {
  const existing = readFileSync(EXPLORER_SCHEMA, "utf-8");
  existingHash = createHash("sha256").update(existing).digest("hex");
} catch {
  // file doesn't exist yet
}

if (existingHash === newHash) {
  console.log("[sync-schema] No drift detected. Explorer schema is up to date.");
  process.exit(0);
}

if (CHECK_MODE) {
  console.error(
    "[sync-schema] DRIFT DETECTED — Explorer schema is out of sync with Runtime schema."
  );
  console.error(
    "Run `npm run db:sync` in apps/pcos-explorer to resync."
  );
  process.exit(1);
}

writeFileSync(EXPLORER_SCHEMA, generated, "utf-8");
console.log(
  `[sync-schema] Synced ${relevant.length} blocks from runtime schema to explorer schema.`
);
console.log(`[sync-schema] Written: ${EXPLORER_SCHEMA}`);
