import { registerDomain } from "@/registry/domain-registry";
import { registerArtifact } from "@/registry/artifact-registry";

registerDomain({
  id: "ontology",
  label: "Ontology",
  description: "Versioned procurement knowledge graph nodes generated by H3 hydration.",
  iconName: "Network",
  href: "/ontology",
  navigationGroup: "cognition",
  artifactTypes: ["OntologyNode"],
  supportedRenderers: ["ontology"],
  primaryModel: "HydrationOntologyNode",
  readiness: "ready",
  coverage: {
    hasData: true,
    hasRenderer: true,
    hasQuery: true,
    hasLineage: true,
    hasValidation: false,
  },
});

registerArtifact({
  artifactType: "OntologyNode",
  domainId: "ontology",
  sourceModel: "HydrationOntologyNode",
  renderer: "ontology",
  label: "Ontology Node",
  description: "A versioned node in the procurement knowledge graph.",
  supportedViews: ["table", "detail"],
  isSearchable: true,
  hasEmbeddings: true,
  isCrossDomain: true,
  readiness: "ready",
  lineage: {
    producedBy: "H3",
    writer: "pcos-runtime",
    hasLineageEvents: true,
    isVersioned: true,
  },
});
