/**
 * Canonical Governance Enums — SpendGuru 2.0
 * @package @sg/governance
 */

export enum RoadmapPosition {
  CRITICAL_PATH = "critical path",
  PARALLEL_PATH = "parallel path",
  DEPENDENCY_UNLOCK = "dependency unlock",
  INFRA_FOUNDATION = "infra foundation",
  CRITICAL_PATH_GATE = "critical path / deadline gate",
}

export enum ReadinessState {
  NOT_READY = "NOT_READY",
  PLANNING = "PLANNING",
  READY = "READY",
  BLOCKED = "BLOCKED",
  IN_PROGRESS = "IN_PROGRESS",
  VALIDATION = "VALIDATION",
  COMPLETE = "COMPLETE",
}

export enum PipelineStatus {
  PLANNED = "PLANNED",
  ACTIVE = "ACTIVE",
  BLOCKED = "BLOCKED",
  COMPLETE = "COMPLETE",
}

export enum ExecutionType {
  ARCHITECTURE = "ARCHITECTURE",
  RUNTIME = "RUNTIME",
  BACKEND = "BACKEND",
  FRONTEND = "FRONTEND",
  DATABASE = "DATABASE",
  AUTH = "AUTH",
  AI = "AI",
  UX = "UX",
  INGESTION = "INGESTION",
  OBSERVABILITY = "OBSERVABILITY",
  EXPORT = "EXPORT",
  GOVERNANCE = "GOVERNANCE",
  DEPLOYMENT = "DEPLOYMENT",
}

export enum ConversationType {
  IMPLEMENTATION = "implementation",
  ARCHITECTURE = "architecture",
  DEBUGGING = "debugging",
  PHILOSOPHY = "philosophy",
  RUNTIME_ANALYSIS = "runtime_analysis",
  ORCHESTRATION = "orchestration",
  UX = "ux",
  CONTINUITY = "continuity",
  GOVERNANCE = "governance",
  INFRASTRUCTURE = "infrastructure",
}

export enum ImportanceLevel {
  LOW = "low",
  MEDIUM = "medium",
  HIGH = "high",
  FOUNDATIONAL = "foundational",
}

export enum ScopeClassification {
  GOVERNANCE = "governance",
  ARCHITECTURE = "architecture",
  IMPLEMENTATION = "implementation",
  AUDIT = "audit",
  PRODUCT = "product",
  DOCUMENTATION = "documentation",
}

export enum FlightRecordFinalStatus {
  SUCCESS = "SUCCESS",
  PARTIAL_SUCCESS = "PARTIAL_SUCCESS",
  FAILED = "FAILED",
}

export enum ArtifactKind {
  CLOSEOUT = "CLOSEOUT",
  EXECUTION_TRAIL = "EXECUTION_TRAIL",
  HANDOFF = "HANDOFF",
  PUBLICATION = "PUBLICATION",
  RUNTIME_SNAPSHOT = "RUNTIME_SNAPSHOT",
}

export enum ArtifactNature {
  PRIMARY = "PRIMARY",
  DERIVED = "DERIVED",
}

export enum ArtifactStatus {
  GENERATED = "GENERATED",
  DELIVERED = "DELIVERED",
  FAILED = "FAILED",
}

export enum GovernanceState {
  VALID = "VALID",
  WARNING = "WARNING",
  FAIL = "FAIL",
}

export enum CloseoutState {
  INITIATED = "INITIATED",
  PENDING_ARTIFACT_CREATED = "PENDING_ARTIFACT_CREATED",
  PENDING_ARTIFACT_VALIDATED = "PENDING_ARTIFACT_VALIDATED",
  PMOS_SAVE_STARTED = "PMOS_SAVE_STARTED",
  PMOS_SAVE_SUCCEEDED = "PMOS_SAVE_SUCCEEDED",
  PMOS_SAVE_FAILED = "PMOS_SAVE_FAILED",
  PMOS_SAVE_PARTIAL = "PMOS_SAVE_PARTIAL",
  VECTOR_REBUILD_STARTED = "VECTOR_REBUILD_STARTED",
  VECTOR_REBUILD_SUCCEEDED = "VECTOR_REBUILD_SUCCEEDED",
  VECTOR_REBUILD_FAILED = "VECTOR_REBUILD_FAILED",
  VECTOR_REBUILD_PARTIAL = "VECTOR_REBUILD_PARTIAL",
  RUNTIME_CONTEXT_VERIFIED = "RUNTIME_CONTEXT_VERIFIED",
  RUNTIME_CONTEXT_VERIFICATION_FAILED = "RUNTIME_CONTEXT_VERIFICATION_FAILED",
  HANDOFF_PUBLICATION_STARTED = "HANDOFF_PUBLICATION_STARTED",
  HANDOFF_PUBLICATION_SUCCEEDED = "HANDOFF_PUBLICATION_SUCCEEDED",
  HANDOFF_PUBLICATION_FAILED = "HANDOFF_PUBLICATION_FAILED",
  CLOSEOUT_COMPLETE = "CLOSEOUT_COMPLETE",
  CLOSEOUT_PARTIAL = "CLOSEOUT_PARTIAL",
  CLOSEOUT_FAILED = "CLOSEOUT_FAILED",
  RECOVERY_REQUIRED = "RECOVERY_REQUIRED",
}

export enum SkillKillSwitchLevel {
  GLOBAL_SKILLS_DISABLED = "GLOBAL_SKILLS_DISABLED",
  ALL_SKILLS_READ_ONLY = "ALL_SKILLS_READ_ONLY",
  ALL_SKILLS_DRY_RUN_ONLY = "ALL_SKILLS_DRY_RUN_ONLY",
  WRITE_BLOCKED = "WRITE_BLOCKED",
  PMOS_WRITE_BLOCKED = "PMOS_WRITE_BLOCKED",
  VECTOR_WRITE_BLOCKED = "VECTOR_WRITE_BLOCKED",
  GOVERNANCE_WRITE_BLOCKED = "GOVERNANCE_WRITE_BLOCKED",
  ROADMAP_WRITE_BLOCKED = "ROADMAP_WRITE_BLOCKED",
  RUNTIME_CONTEXT_WRITE_BLOCKED = "RUNTIME_CONTEXT_WRITE_BLOCKED",
  PROMPT_INJECTION_BLOCKED = "PROMPT_INJECTION_BLOCKED",
  AUTO_PASS_BLOCKED = "AUTO_PASS_BLOCKED",
  MANUAL_APPROVAL_REQUIRED = "MANUAL_APPROVAL_REQUIRED",
  RECOVERY_REQUIRED = "RECOVERY_REQUIRED",
  SINGLE_SKILL_DISABLED = "SINGLE_SKILL_DISABLED",
  SINGLE_SKILL_DRY_RUN_ONLY = "SINGLE_SKILL_DRY_RUN_ONLY",
  SINGLE_SKILL_READ_ONLY = "SINGLE_SKILL_READ_ONLY",
}

export enum SkillExecutionMode {
  DISABLED = "DISABLED",
  READ_ONLY = "READ_ONLY",
  DRY_RUN_ONLY = "DRY_RUN_ONLY",
  LIMITED_EXECUTION = "LIMITED_EXECUTION",
}

export enum KillSwitchFailureMode {
  FAIL_CLOSED = "FAIL_CLOSED",
}

export enum DryRunMode {
  DISABLED = "DISABLED",
  DIAGNOSTIC_ONLY = "DIAGNOSTIC_ONLY",
  ADVISORY_ONLY = "ADVISORY_ONLY",
}

export enum DryRunScope {
  GLOBAL = "GLOBAL",
  SINGLE_SKILL = "SINGLE_SKILL",
}

export enum DryRunVerdict {
  PASS = "PASS",
  FAIL = "FAIL",
  REQUIRES_REVIEW = "REQUIRES_REVIEW",
}

export enum DryRunBlockReason {
  WRITE_SURFACE_BLOCKED = "WRITE_SURFACE_BLOCKED",
  KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE",
  APPROVAL_REQUIRED = "APPROVAL_REQUIRED",
  RECOVERY_REQUIRED = "RECOVERY_REQUIRED",
}

export enum DryRunActionType {
  FILE_READ = "FILE_READ",
  FILE_WRITE = "FILE_WRITE",
  COMMAND = "COMMAND",
  PMOS_SAVE = "PMOS_SAVE",
  VECTOR_REBUILD = "VECTOR_REBUILD",
}

export enum DryRunMutationSurface {
  PMOS = "PMOS",
  VECTOR = "VECTOR",
  GOVERNANCE = "GOVERNANCE",
  RUNTIME_CONTEXT = "RUNTIME_CONTEXT",
  FILESYSTEM = "FILESYSTEM",
}

export enum ExecutionTrailEventType {
  TASK_RECEIVED = "TASK_RECEIVED",
  PROMPT_CAPTURED = "PROMPT_CAPTURED",
  PLAN_DECLARED = "PLAN_DECLARED",
  FILE_READ = "FILE_READ",
  FILE_SEARCHED = "FILE_SEARCHED",
  COMMAND_PLANNED = "COMMAND_PLANNED",
  COMMAND_EXECUTED = "COMMAND_EXECUTED",
  COMMAND_SUCCEEDED = "COMMAND_SUCCEEDED",
  COMMAND_FAILED = "COMMAND_FAILED",
  PATCH_PLANNED = "PATCH_PLANNED",
  VALIDATION_STARTED = "VALIDATION_STARTED",
  VALIDATION_SUCCEEDED = "VALIDATION_SUCCEEDED",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  RETRY_STARTED = "RETRY_STARTED",
  RETRY_COMPLETED = "RETRY_COMPLETED",
  DECISION_RECORDED = "DECISION_RECORDED",
  RISK_RECORDED = "RISK_RECORDED",
  ARTIFACT_CREATED = "ARTIFACT_CREATED",
  PATCH_APPLIED = "PATCH_APPLIED",
  PATCH_FAILED = "PATCH_FAILED",
  PENDING_ARTIFACT_CREATED = "PENDING_ARTIFACT_CREATED",
  PMOS_SAVE_STARTED = "PMOS_SAVE_STARTED",
  PMOS_SAVE_SUCCEEDED = "PMOS_SAVE_SUCCEEDED",
  PMOS_SAVE_FAILED = "PMOS_SAVE_FAILED",
  VECTOR_REBUILD_STARTED = "VECTOR_REBUILD_STARTED",
  VECTOR_REBUILD_SUCCEEDED = "VECTOR_REBUILD_SUCCEEDED",
  VECTOR_REBUILD_FAILED = "VECTOR_REBUILD_FAILED",
  HANDOFF_PUBLICATION_STARTED = "HANDOFF_PUBLICATION_STARTED",
  HANDOFF_PUBLICATION_SUCCEEDED = "HANDOFF_PUBLICATION_SUCCEEDED",
  HANDOFF_PUBLICATION_FAILED = "HANDOFF_PUBLICATION_FAILED",
  RECOVERY_REQUIRED = "RECOVERY_REQUIRED",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_INCOMPLETE = "TASK_INCOMPLETE",
  CLOSEOUT_COMPLETED = "CLOSEOUT_COMPLETED",
}

export enum ExecutionTrailEventStatus {
  DECLARED = "DECLARED",
  RECORDED = "RECORDED",
  STARTED = "STARTED",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  PARTIAL = "PARTIAL",
  BLOCKED = "BLOCKED",
  COMPLETE = "COMPLETE",
  INCOMPLETE = "INCOMPLETE",
  NOT_APPLICABLE = "NOT_APPLICABLE",
}

export enum ExecutionTrailEventSeverity {
  INFO = "INFO",
  WARNING = "WARNING",
  ERROR = "ERROR",
  CRITICAL = "CRITICAL",
}

export enum ExecutionTrailStatus {
  MISSING = "MISSING",
  PARTIAL = "PARTIAL",
  PRESENT = "PRESENT",
}

export enum FactPreservationStatus {
  MISSING = "MISSING",
  PARTIAL = "PARTIAL",
  BASELINE_PRESENT = "BASELINE_PRESENT",
}